server:
  port: 7070

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
#  cloud:
#    consul:
#      discovery:
#        prefer-ip-address: true
#        ip-address: host.docker.internal
#        hostname: host.docker.internal
#        service-name: gateway-service
#        health-check-path: /actuator/health
#        health-check-interval: 15s
#        instance-id: gateway-service-7070
#        register: true
#        enabled: true
    gateway:
      server:
        webflux: # Cấu trúc mới
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
              filters:
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


#springdoc:
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - name: Gateway
#        url: /v3/api-docs
#      - name: User Service
#        url: /user-service/api/v3/api-docs
#      - name: Project Service
#        url: /project-service/api/v3/api-docs
