server:
  port: 7071
  servlet:
    context-path: /api

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/kbdb
    username: kbuser
    password: kbpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: user


#  cloud:
#    consul:
#      discovery:
#        prefer-ip-address: true
#        ip-address: host.docker.internal
#        hostname: host.docker.internal
#        service-name: user-service
#        health-check-path: /api/actuator/health
#        health-check-interval: 15s
#        instance-id: user-service-7071
#        register: true
#        enabled: true
#logging:
#  level:
#    org.springframework.cloud.consul: TRACE
#    org.springframework.cloud.consul.discovery: TRACE


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


openapi:
  server-url: http://localhost:7071/user-service/api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true
