spring:
  data:
    redis:
      host: kb_redis
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER}
  instance:
    prefer-ip-address: true


openapi:
  server-url: http://${USER_SERVICE}:7071/user-service/api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true


host:
  backend-host: http://S{GATEWAY_SERVICE}:7070/user-service/api
  handle-verification-url: /auth/verify-account
