server:
  port: 7071
  servlet:
    context-path: /api

spring:

  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: kb_user
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
#      s3:
#        bucket: hamster-application
      sqs:
        region: ${AWS_REGION}
        email-queue: ${AWS_SQS_EMAIL_QUEUE}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  duration: ${JWT_DURATION}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true

