server:
  servlet:
    context-path: /api
  port: 7072

spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://localhost:5432/kbdb
    username: kbuser
    password: kbpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: kb_project

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: project-service
        register: true
        enabled: true
        health-check-path: /actuator/health
        health-check-interval: 10s
# ...existing config...

openapi:
  server-url: http://localhost:7072/project-service/api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: methods
    tags-sorter: alpha
    display-request-duration: true
    default-model-expand-depth: 10
    display-operation-id: true